# Generated by Django 5.0.3 on 2024-03-23 11:22

import utils.utils_time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_time', models.FloatField(default=utils.utils_time.get_timestamp)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='user_user_name_e29f28_idx')],
            },
        ),
    ]
